import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";
import {Inter} from 'next/font/google'



const fontSerif = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-serif",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fontSerif.variable)}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
